replicaCount: 1

deploymentName: python-app
serviceName: python-svc
ingressName: python-ingress
hpaName: python-app-hpa

image:
  repository: devopskarthik123/python-kub
  pullPolicy: IfNotPresent
  tag: v02

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 4000

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: www.devopslearning.live
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ingress-testing
      hosts:
        - www.devopslearning.live

resources: 
  limits:
    cpu: "500m"
    memory: "500Mi"
  requests:
    cpu: "500m"
    memory: "500Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: python-pvc

volumeMounts:
  - name: data-volume
    mountPath: /tmp

nodeSelector: {}

tolerations: []

affinity: {}
